### ISSUE TITLE
downloads posts

### ISSUE THREAD

**Issue by wullien** [oxpus/Download-Extention#18]
you closed the other issue before i could say i got that working it is just i want each download to be put in a different forum like if i had 3 forums

Films, Music, Sheep, 
and i uploaded a film i would want it to post in films
and i uploaded Music i would want it to post in Music
and i uploaded a Sheep i would want it to post in Sheep

but the way it is set if you upload it will only put it in the selected forum is there a way to work it so that it will post in a different forums

**Comment by oxpus** [comment]
If you seperate fils, music and sheep into different download categories you can set for each category a seperate forum to post the topics.
To do this, change the setting "Choose a forum the topics:" in the ACP unter General Configuration > Topics to "Category Select" and then in each download category within the Category Management you can select the forum in which the topics should be posted.
In the categories you will get the "topic" section and there you can select with the option "Choose a forum the topics from this download category" your wanted forum.

And because this you can find in the online help system in the extention, too, I've closed the first and will close this post, too.
